// Crypto Reca v0.4.5 — Decision Matrix + correlation/cluster risk
(function(){'use strict';const C=window.CR4,A=C.a,N=C.num;
const radar=a=>A(state.radar).find(x=>x.asset===a)||{},risk=p=>p?state?.positionRisk?.positions?.[p.id]||null:null;
function trend(asset){const t=state?.multiTimeframeTrend?.[asset];if(t)return t;const s=A(market?.series?.[asset]),c=s.map(x=>N(x.c)).filter(x=>x!=null);const sl=k=>c.length>k?(c.at(-1)>c.at(-1-k)*1.003?'ALCISTA':c.at(-1)<c.at(-1-k)*.997?'BAJISTA':'NEUTRAL'):'—';return {'15m':'—','1H':sl(3),'4H':sl(8),'1D':sl(Math.min(24,Math.max(1,c.length-1)))} }
function matrix(){return `<div class="section-title"><h2>Decision Matrix</h2><span>capas independientes</span></div>${A(state.radar).map(r=>{const p=A(state.positions).find(x=>x.asset===r.asset&&x.status==='OPEN'),pr=risk(p),nw=A(state?.newsOverlay?.items).find(x=>A(x.assets).includes(r.asset)&&['HIGH','CRITICAL'].includes(x.impactLevel)),ex=state?.externalSignals?.consensusByAsset?.[r.asset]||'NONE',t=trend(r.asset);return `<div class="decision-card"><div class="row"><div><strong>${esc(r.asset)}</strong><div class="tiny">${esc(r.decision||'NO SETUP')}</div></div><span class="badge ${String(r.decision).includes('HOLD')?'open':'watch'}">${esc(r.decision||'—')}</span></div><div class="decision-grid"><div><small>ERS</small><strong>${r.ers==null?'NO CALCULADO':`${r.ers}/100`}</strong></div><div><small>Entry</small><strong>${r.entryConfirmation==null?'—':`${r.entryConfirmation}/5`}</strong></div><div><small>D / E</small><strong>${esc(r.d||'—')} / ${esc(r.e||'—')}</strong></div><div><small>PRS</small><strong>${pr?`${pr.prs} · ${esc(pr.action)}`:'—'}</strong></div><div><small>15m / 1H</small><strong>${esc(t['15m']||t.m15||'—')} / ${esc(t['1H']||t.h1||'—')}</strong></div><div><small>4H / 1D</small><strong>${esc(t['4H']||t.h4||'—')} / ${esc(t['1D']||t.d1||'—')}</strong></div><div><small>Noticias</small><strong>${nw?`${esc(nw.impactLevel)} · ${esc(nw.action||'WATCH')}`:'NONE'}</strong></div><div><small>Gurús</small><strong>${esc(ex)}</strong></div></div></div>`}).join('')}<div class="card info-card"><strong>Regla</strong><p>Estas capas no se promedian. ERS mide calidad, Entry timing, tendencia contexto, PRS riesgo de posición, y noticias/gurús son overlays. La decisión contemporánea de Crypto Reca manda.</p></div>`}
function ret(a){const c=A(market?.series?.[a]).map(x=>N(x.c)).filter(x=>x!=null),r=[];for(let i=1;i<c.length;i++)r.push(c[i]/c[i-1]-1);return r.slice(-48)}
function corr(x,y){const n=Math.min(x.length,y.length);if(n<12)return null;x=x.slice(-n);y=y.slice(-n);const mx=x.reduce((s,v)=>s+v,0)/n,my=y.reduce((s,v)=>s+v,0)/n;let z=0,xx=0,yy=0;for(let i=0;i<n;i++){const a=x[i]-mx,b=y[i]-my;z+=a*b;xx+=a*a;yy+=b*b}return xx&&yy?z/Math.sqrt(xx*yy):null}
function correlation(){const assets=[...new Set(A(state.radar).map(r=>r.asset))],pairs=[];for(let i=0;i<assets.length;i++)for(let j=i+1;j<assets.length;j++){const c=corr(ret(assets[i]),ret(assets[j]));if(c!=null)pairs.push([assets[i],assets[j],c])}const op=A(state.positions).filter(p=>p.status==='OPEN'),sum=q=>q.reduce((s,p)=>s+(N(p.entry)||0)*(N(p.qty)||0),0),total=sum(op),core=sum(op.filter(p=>['BTC','ETH'].includes(p.asset))),beta=sum(op.filter(p=>['SOL','AVAX','SUI'].includes(p.asset))),avg=pairs.length?pairs.reduce((s,x)=>s+x[2],0)/pairs.length:null;return `<div class="section-title"><h2>Correlation & Cluster Risk</h2><span>48h 1H</span></div><div class="grid metrics"><div class="card"><div class="metric-label">Crypto total</div><div class="metric-value">${money(total)}</div></div><div class="card"><div class="metric-label">BTC+ETH Core</div><div class="metric-value">${money(core)}</div></div><div class="card"><div class="metric-label">High beta</div><div class="metric-value">${money(beta)}</div></div><div class="card"><div class="metric-label">Correlación media</div><div class="metric-value">${avg==null?'—':money(avg)}</div></div></div>${pairs.length?`<div class="correlation-list">${pairs.sort((a,b)=>b[2]-a[2]).map(x=>`<div><span>${x[0]} / ${x[1]}</span><strong>${money(x[2])}</strong></div>`).join('')}</div>`:'<div class="empty card">Muestra insuficiente.</div>'}`}
C.registerScreen('matrix','Decision Matrix',matrix);C.registerScreen('correlation','Correlación',correlation);
})();
